openapi: 3.1.0
info: 
  title: OAS Specification - Federation agricole
  version: 1.0.0
servers: 
- url: http://localhost:8080
tags:
  - name: Collectivite
  - name: Membre
  - name: Cotisation
  - name: Compte
paths:
  /collectivite/new:
    post:
      tags: 
        - Collectivite
      description: put new collective in the federation
      requestBody:
        description: membre necessary for the creation of the groupe
        content:
          application/json:
            schema:
              type: array 
              items: 
                $ref: '#/components/schemas/Membre'
      parameters:
        - name: autorisation
          in: header
          description: authorization from the federation
          required: true
          schema:
            type: string
        - name: localisation
          in: header
          description: location of the new collectivite
          required: true
          schema:
            type: string
      responses:
        200:
          description: collective created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collectivite'
  /membre/add:
    post:
      tags:
        - Membre
      description: add a new membre to the federation
      requestBody:
        description: necessary element needed to the admission
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AdmissionMembre'
      parameters:
        - name: frais
          in: header
          description: the ref needed to be add
          required: true
          schema:
            type: string
      responses:
        200: 
          description: add the new membre in the federation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Membre'
  /cotisation:
    get:
      tags:
        - Cotisation
      description: get the cotisation
      responses:
        200:
          description: the payment has been confirmed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Cotisation'
                example: the payment has been confirmed
  /cotisation/{id}/pay:
    put:
      tags:
        - Cotisation
      description: pay the cotisation
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        description: necessary element to confirm the cotisation
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Paiment'
      responses:
        200:
          description: the payment has been confirmed
          content:
            text/plain:
              schema:
                type: string
                example: the payment has been confirmed
  /federation/compte:
   get:
    tags:
      - Federation
      - Compte
    description: Get the compte information of the federation
    responses:
      200:
        description: compte information
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FederationCompte"
  /collectivite/compte:
   get:
    tags:
      - Collectivite
      - Compte
    description: Get the compte information of all collective
    responses:
      200:
        description: compte information
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CollectiviteCompte'
  /collectivite/{id}/compte:
   get:
    tags:
      - Compte
      - Collectivite
    description: Get the compte information of a collective
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    responses:
      200:
        description: compte information
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CollectiviteCompte'
  /activite:
   get:
    description: know all the activite of the month
    responses:
      200:
        description: get all the activite 
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Activite'
  /activite/{id}/valide:
    post:
      description: Valide the participation of a member
      requestBody:
        description: Data about the member
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Membre'
      responses:
        200:
          description: valide the participation
          content:
            text/plain:
              schema:
                type: string
                example: member {name} is conformt to have participate the {name} activity 
components:
  schemas:
    Federation:
      type: object
      properties:
        Dirigant:
          $ref: '#/components/schemas/Membre'
        ListOfAdjoint:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        ListOfTresearer:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        ListOfSecretairies:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        ListOfCollectivite:
          type: array
          items: 
            $ref: '#/components/schemas/Collectivite' 
    FederationCompte:
      type: object
      properties:
        Caisse:
          $ref: '#/components/schemas/CompteCaisse'
        ListOfCompteBancaire:
          type: array
          items:
           $ref: '#/components/schemas/CompteBancaire'
        ListOfCompteMobile:
          type: array
          items:
           $ref: '#/components/schemas/CompteMobile'
    Collectivite:
      type: object
      properties:
        id: 
          type: integer
        nom:
          type: string
        specialisation:
          type: string
        dateDeCreation:
          type: string
        localisation:
          type: string
        listOfMembre:
          type: array
          items:
            $ref: '#/components/schemas/Membre'
        listOfCotisation:
          type: array
          items: 
            $ref: '#/components/schemas/Cotisation'
    CollectiviteCompte:
      type: object
      properties:
        Caisse:
          $ref: '#/components/schemas/CompteCaisse'
        ListOfCompteBancaire:
          type: array
          items:
           $ref: '#/components/schemas/CompteBancaire'
        ListOfCompteMobile:
          type: array
          items:
           $ref: '#/components/schemas/CompteMobile'
    Membre:
      type: object
      properties:
        nom: 
          type: string
        prenom:
          type: string
        dateDeNaissance:
          type: string
        genre:
          type: string
          enum:
            - M
            - F
        adresse:
          type: string
        metier:
          type: string
        telephone:
          type: string
        adressseMail:
          type: string
        dateDAdhesion:
          type: string
        post:
          type: string
          enum:
            - President
            - President adjoint
            - Tresorier
            - Secretaire
            - Membre confirme
            - Membre junior
    AdmissionMembre:
      type: object
      properties:
        parrainMembre:
          $ref: '#/components/schemas/Membre'
        nom:
          type: string
        prenom:
          type: string
        dateDeNaissance:
          type: string
        genre:
          type: string
          enum:
            - M
            - F
        adresse:
          type: string
        metier:
          type: string
        telephone:
          type: string
        adresseMail:
          type: string
    Cotisation:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        encaissement:
          $ref: '#/components/schemas/Encaisement'
        periodisite:
          type: string
          enum:
            - Mensuelle
            - Annuelle
            - Ponctuelle
    Encaisement:
      type: object
      properties:
        dateDEncaissement:
          type: string
        montant:
          type: number
          format: decimal
        modeDePaiment:
          type: string
          enum: 
           - Espece
           - Virement
           - MobileMoney
    Paiment:
      type: object
      properties:
        id:
          type: string
        montant:
          type: number
          format: decimal
        modeDePaiment:
          type: string
          enum:
            - Espece
            - Virement
            - MobileMoney
    CompteCaisse:
      type: object
      properties:
        id:
          type: string
        montant:
          type: number
          format: decimal
    CompteBancaire:
      type: object
      properties:
        id: 
          type: string
        banqueName:
          type: string
          enum:
            - BRED
            - MCB 
            - BMOI 
            - BOA
            - BGFI
            - AFG
            - ACCÈS BANQUE
            - BAOBAB
            - SIPEM
        numeroCompte:
          type: string
        montant:
          type: number
          format: decimal
    CompteMobile:
       type: object
       properties:
        id:
          type: string
        nameTitulaire:
          type: string
        numeroTitulaire:
          type: string
        nameSevrice:
          type: string
          enum:
            - OrangeMoney
            - Mvola
            - AirtelMoney
        numeroTelephone:
          type: string
        montant:
          type: number
          format: decimal
    Activite:
      type: object
      properties:
        name:
          type: string
        date:
          type: string
        perioditite:
          $ref: '#/components/schemas/Perioditite'
        ListOfMember:
          type: array
          items:
            $ref: '#/components/schemas/MembreValide'
    Perioditite:
      type: object
      properties:
        intervalle:
          type: string
          enum:
            - Semaine
            - Mois
        numberDIntervalle:
          type: integer
    MembreValide:
      type: object
      properties:
        aParticiper:
          type: boolean
        membre:
          $ref: "#/components/schemas/Membre"
        

        